language: node_js
node_js:
  - '11'
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - PGPORT=5432
script:
  - yarn run coveralls